### ISSUE TITLE
Show number of results returned on requirements/policy view

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#236]
Why: Helps users understand how the filter mechanisms are working

Should probably include total count per latest mockups, too.

**Comment by micahtaylor** [comment]
Is this count cover under these:
Policy listing - https://gsa.invisionapp.com/share/M6AU3YB49#/229078016_Policy_Listing
Req listing - https://gsa.invisionapp.com/share/M6AU3YB49#/229078015_Requirement_Listing

**Comment by theresaanna** [comment]
Should this issue get rolled up into one something like "Implement requirements list view changes"? @micahtaylor @tadhg-ohiggins

**Comment by micahtaylor** [comment]
I suppose it could.

**Comment by tadhg-ohiggins** [comment]
Some screenshots of my current implementation:

Requirements, all:
![image](https://cloud.githubusercontent.com/assets/2626258/25973734/3b0af2e4-365a-11e7-94a8-677aa3194d56.png)

Requirements, filtered by topic:
![image](https://cloud.githubusercontent.com/assets/2626258/25973340/88b47d0a-3658-11e7-9500-a0bed8208f9f.png)

Requirements, no results:
![image](https://cloud.githubusercontent.com/assets/2626258/25973822/a87d626c-365a-11e7-8d4e-b7eacc05956b.png)

Policies, all:
![image](https://cloud.githubusercontent.com/assets/2626258/25973749/544a3a44-365a-11e7-9791-db681031f04a.png)

Policies, filtered by topic:
![image](https://cloud.githubusercontent.com/assets/2626258/25973786/6e5e3cf0-365a-11e7-9702-f6d5c5d030e9.png)

Policies, no results:
![image](https://cloud.githubusercontent.com/assets/2626258/25973805/89ddb924-365a-11e7-8bae-b7deda43a312.png)

**Comment by nicoleslaw** [comment]
We discussed this in Slack, but I would recommend that we show the full number of policies on load, and then narrow that with the search.

After talking through it, I find a nice example with GOV.UK: 

`101,433 publications` on load
`3,075 publications containing technology` after filtering

https://www.gov.uk/government/publications

https://www.gov.uk/government/publications?keywords=technology&publication_filter_option=all&topics%5B%5D=all&departments%5B%5D=all&official_document_status=all&world_locations%5B%5D=all&from_date=&to_date=

**Comment by micahtaylor** [comment]
Adding @carodew to run with this one so we can get consensus. 🎉  
She will likely ping @nicoleslaw and @tadhg-ohiggins to get an understanding of the issue.

**Comment by carodew** [comment]
So basically it sounds like (from the convo here and from the convo in the team Slack channel) that it's a little unclear what user needs we're trying to fill on a more granular level of helping users "understand how the filter mechanisms are working."

So I actually think there is a piece there that is important. Every micro-interaction should provide some feedback to the user that their action had whatever result it had, and the number of results is part of filling that feedback need. There's other real nerdy stuff about how users behave when performing searches or filtering that I won't get into too deeply, but basically involves checking the results of the search to see if they've performed it correctly, then going back to revise the search if needed. 

## Hypothesis 
> As an Agency Implementer, when I filter the list of requirements, I want to know how many results I'm getting back so I know if I need to revise my filter or search criteria.

## How we'll know we're right
> In usability testing, we observe people looking at or noticing the number of search results before tweaking their filters (this will probably be subtle).  

## Recommendations

### Requirements page, filtered

`{ total # in this search } requirements match your search.`

#### Examples
 - `30 requirements match your search.` 
 - `One requirement matches your search.` _(if you want to be fancy you can spell out numbers 1-9 as one, two, etc., otherwise a numeral is fine)_
 - `No requirements match your search, try removing some filters.` _(note emphasis on next action to take)_

### Requirements page, unfiltered

An Implementer (usually) only gets here after they've removed all their filters. In that sense, it's helpful for them to see the number of requirements as feedback that they've applied zero filters and this is the result. 

`{ total # of requirements } requirements.` 

#### Example
 `2,035 requirements`

## Policy page

Follow precedent of Requirements page

Filtered –

`{total # in search} policies match your search`
`{total # of policies} policies`
`No policies match your search, try removing some filters.`

Unfiltered – 
`{ total # of policies } policies.` 

## Reasoning

Note that any user coming through the home page will first see the requirements page in a filtered view.

The first number in Micah's mock up is `{ total # in this search } ` tells the Agency Implementer that they either need to change their search parameters or that they have gotten a reasonable number of requirements that they can start reading through. if there are 30,000 results, the Implementer probably will want to filter it down more. If 0, they'll want to remove filters. 

![omb-number-of-things](https://user-images.githubusercontent.com/10144074/26849519-82c11802-4ad2-11e7-9649-d2eea3dfc24c.png)

I believe that the { total number of requirements in the database } _in the filtered view_ doesn't really help the user know what action to take next, so I don't think it's needed. Or rather, unless and until we observe users getting confused while searching requirements and we have a strong hypothesis that this would help, I think we should leave it out. 

Page numbers and # results per page are about navigation, not tweaking the search criteria, so I think they are most likely to cause confusion here.

**Comment by cmc333333** [comment]
Did #417 resolve?

**Comment by tadhg-ohiggins** [comment]
I think so, but I vote for keeping this open until @carodew gives the okay on the UI.

**Comment by carodew** [comment]
Yayyy!!! 

Two changes though (trying to live up to @jehlers legacy) – 

1. Change "Policy" to lowercase, so the entire phrase is sentence case (requirements is already like this). I'm assuming fixing this here will also fix the capitalization in the 'no Policies match your search' message, which should also be lowercase. 

<img width="394" alt="lc-policy" src="https://user-images.githubusercontent.com/10144074/27484755-6b528722-57f8-11e7-88e1-c402533771e4.png">

2. When there are no filters or searches applied, it should just say "241 policies." Right now is says "241 policies match your search." which is a little confusing because there is no search applied. Same goes for requirements.

**Comment by cmc333333** [comment]
For 2, I suspect the filter is present but empty (to recreate, try starting from the homepage or add a filter then remove it). We can add that check to the logic which determines whether or not to include "match your search".

**Comment by carodew** [comment]
Well I started from the home page, picked a topic, then removed it, and still had the "matched your search" part of the phrase.

**Comment by cmc333333** [comment]
Sorry @carodew, those were directions for @tadhg-ohiggins.

**Comment by carodew** [comment]
😜

**Comment by cmc333333** [comment]
Resolved with #418
