### ISSUE TITLE
Unable to restore deleted policy

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#374]
On my local build, I was unable to restore any deleted policies even though I deleted a few. 

## Steps to recreate 
1. Through the admin interface, I deleted a few policies, confirmed in the recent actions log: 
![image](https://cloud.githubusercontent.com/assets/10144074/26802594/126af906-4a0f-11e7-93e2-a4692bdc310b.png)

2. from the Policies list page, I clicked on "Recover deleted policies:"  
![image](https://cloud.githubusercontent.com/assets/10144074/26802868/1df9ebd2-4a10-11e7-992b-a146148fc324.png)

3. However,  the next page doesn't show any deleted policies to recover: 
![image](https://cloud.githubusercontent.com/assets/10144074/26802916/50dcb4bc-4a10-11e7-91d5-b378c8ae0784.png)

**Comment by carodew** [comment]
Please let me know if I can provide more info.

**Comment by tadhg-ohiggins** [comment]
While I haven't been able to reproduce this problem locally, I have found some other history-related issues that I'm going to keep here until we have somewhere else to put them:

- [ ] The contents of `issuing_body` aren't stored in history, presumably because the script that added it didn't `save()` inside of a `reversion.create_revision()` decorator/context manager—something we should keep in mind for future changes.
- [ ] Deleting a policy object deletes (after warning you) all of its related requirement objects, which is what we want. However, restoring the policy object via history doesn't restore them—you have to go to the **Recover Deleted Requirements** section and restore them one by one. We may have to live with this, but it's problematic for policies with many requirements.
- [ ] Requirements don't save their topics, so those relationships cannot be restored after deletion (or other changes). This is likely due to my not setting up the relationships correctly as described here: <https://django-reversion.readthedocs.io/en/release-1.8.1/api.html#advanced-model-registration>. I think this is important to fix.

**Comment by tadhg-ohiggins** [comment]
I'll try to reproduce the original bug on a different machine, too.

**Comment by cmc333333** [comment]
I wonder if the original bug came from not having the initial set of revisions? Restarting the server creates those revisions, but maybe we had an order-of-operations issue?

Agreed that we should save imported reqs/policies/topics w/ the revision library.

**Comment by carodew** [comment]
I'm happy to Do Things and retest if that's helpful at all.

**Comment by cmc333333** [comment]
Re: "The contents of issuing_body aren't stored in history":

I'd bet that's because the field was moved recently within the database. I wonder if we can programatically create a new version of every policy just to catch up.

Re: "Requirements don't save their topics"

Let's get off django-taggit and just use a simple many-to-many relationship. Taggit did some things nicely, but in #282, we've been asked to remove most of that functionality anyway.

**Comment by cmc333333** [comment]
We'll need to verify that topics aren't restoring correctly (that could be a consequence of taggit), but I *think* the other issues are a result of schema changes/data migrations. We'll likely want a larger solution to account for these sort of schema changes.

**Comment by cmc333333** [comment]
I've verified that topics are lost even when attached to a brand new, non-schema-migrated requirement, while agencies *are* maintained.

**Comment by cmc333333** [comment]
Underlying issues were fixed w/ #398, #400, #406.
