### ISSUE TITLE
requirement text highlighted within full policy view (design only)

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#529]
As an agency implementer, I want to quickly find the specific actions agencies need to take within the policy text, so I can easily skip past the content that doesn't mean anything to me. However I want to see the requirements within context of the policy so I can better understand their intent. 

## ac 
- [ ] users can quickly scan and see which bits of text constitute a requirement
- [ ] users can articulate what a 'requirement' is based on information in the UI (and why the text is called out)

**Comment by carodew** [comment]
From demo convo on 10/20 – this is a really nice to have, but not a requirement for the first iteration.

**Comment by rtwell** [comment]
a couple thoughts:
it would be great if there was an indicator that the beginning and the end of the requirement. 
i had a pretty pale yellow there before, and i think it could be darker/more vibrant so that older screens can render it (i used a similar color on plainlanguage.gov and we got feedback that old monitors had a hard time rendering it)

![image](https://user-images.githubusercontent.com/12564977/33273329-9625e1c6-d352-11e7-927d-01f990526475.png)

**Comment by cmc333333** [comment]
@rtwell does this design replace #619?

**Comment by rtwell** [comment]
it updates it, yes
