### ISSUE TITLE
Search results updates

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#543]
Change full text search box to be the results page

**Comment by rememberlenny** [comment]
The description here is pretty vague. 

Is there anything more to this? @cmc333333 @yowill

**Comment by cmc333333** [comment]
<img width="1242" alt="screen shot 2017-10-10 at 1 35 41 pm" src="https://user-images.githubusercontent.com/326918/31455506-c01bcadc-ae85-11e7-98fc-ffde029dacd1.png">
This highlights places on the policy page which link to the requirements page.

First priority is to change the default for the full text search so that it defaults to giving results on the policy tab. You should be able to search from the home page or privacy policy page and be taken directly to the policy tab.

Second priority is to disable the Requirements tab. This can be done by removing the other links I've highlighted in that screenshot, but we'll want to check in w/ design about how to replace them. It doesn't make much sense to have a big circle around non-clickable text, for example.

**Comment by rememberlenny** [comment]
This is very clear! Thank you CM!

--
*Leonard Bogdonoff*
rememberlenny@gmail.com
Blog <http://blog.rememberlenny.com> | Portfolio <http://rememberlenny.com/>
 | @rememberlenny <http://twitter.com/rememberlenny>
949-322-8496
