### ISSUE TITLE
Policy detail: Policy number in url

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#551]
The policy detail page is currently accessible at `/policy/{policy_id}`. Many (but not all) polices have a more meaningful policy number (like "A-130" or "M-16-19") which would be better to key off. Let's ignore the corner case around numbers like "A-136 Revised" and check for `[AM]-[0-9-]+` in the canonical URL. This is currently stored in the `omb_policy_id` field on `Policy`.

**Comment by krues8dr** [comment]
We have policies that do not have numbers, unfortunately. E.g. [this](https://obamawhitehouse.archives.gov/sites/default/files/omb/assets/egov_docs/release_memo_-_planning_guide_roadmap_toward_ipv6_adoption_052009.pdf). I'd love to see us move to using a slug here instead of IDs, universally, which defaults to the policy number or a slugified title in absence of that.

**Comment by cmc333333** [comment]
We'll aim to get to both this sprint, but I've split of the slug-related things into #575. For this ticket, we just want them accessible by their policy number (e.g. M-16-19) when present. We'll continue to allow access via policy id.

**Comment by cmc333333** [comment]
Looks like we'll need to tweak the UI as well -- maybe just the routers file?

* https://omb-eregs-demo.app.cloud.gov/policy/M-16-19 gives a 404 but
* https://omb-eregs-api-demo.app.cloud.gov/policies/M-16-19/ works

**Comment by rememberlenny** [comment]
On it!

**Comment by rememberlenny** [comment]
This should be finished up with #598
