### ISSUE TITLE
Wireframe definitions feature

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#60]
Problem: Like in regulations and most other legal documents, OMB policy documents have words that are specifically defined. However, these terms may be defined across various documents and statutes and are hard to find.

> “‘Information’ means fundamentally different things in different documents. You need 3 statutes, 2 docs, 1 appendix to understand ‘information system.’”

**Comment by jehlers** [comment]
In our research, we heard that defined terms were very hard to keep track of because they span policy documents (and potentially statutes), and can be defined differently in different documents.

In eRegs we have a few features that will help alleviate these problems:
- Collecting definitions from where ever they are defined and displaying them in the context of where the user is reading (in the right sidebar) 
- Calling out (by grey underline) which terms are defined
- Scoping definitions and showing the correct one where it applies

I have not quite "wireframed" a solution for this new tool yet, but due to the complexity of the OMB policy definitions problem, I think the beta.fec.gov glossary tool could be an MVP-type solution.

### Definitions captured in-line and displayed in context of what the user is reading

Just like the eRegs tool, FEC's glossary show's users which terms are defined by using a little 📖 icon. 

![screen shot 2017-02-23 at 5 25 26 pm](https://cloud.githubusercontent.com/assets/4267825/23309905/83d5c94e-fa7e-11e6-97dc-54839e7bd4a8.png)

When the user clicks on that term, the definition flows in from the right meeting the user where they are in their research process.

![screen shot 2017-02-23 at 5 25 43 pm](https://cloud.githubusercontent.com/assets/4267825/23309944/a04db974-fa7e-11e6-9ef0-2c2de1b753fb.png)

### Ever-present definition search

The biggest difference between eRegs' definition feature and FEC's glossary is that FEC's glossary is always accessible. 

![screen shot 2017-02-23 at 5 26 15 pm](https://cloud.githubusercontent.com/assets/4267825/23310027/fa36296c-fa7e-11e6-9c2d-c156b10a59a2.png)

When the user clicks on the glossary in the header, the same definitions sidebar flows in from the right. But this time, all the terms that FEC has defined are in a list, and the user can either browse for or search/filter down which one they are looking for.

![screen shot 2017-02-23 at 5 26 37 pm](https://cloud.githubusercontent.com/assets/4267825/23310061/2243b0dc-fa7f-11e6-81b1-3576b0584e11.png)

![screen shot 2017-02-23 at 5 26 49 pm](https://cloud.githubusercontent.com/assets/4267825/23310076/30368160-fa7f-11e6-869d-c0225b4ca644.png)

![screen shot 2017-02-23 at 5 27 02 pm](https://cloud.githubusercontent.com/assets/4267825/23310079/3627e6c2-fa7f-11e6-9f12-e51f2771ecdc.png)

If we had this kind of ever-present glossary feature for OMB policy, people could potentially start their search looking for a specific defined term and see the definition (or definitions). Then if they want to dig deeper, they could be taken from the definition to the document(s) they apply to or are defined in. 

In addition, I really like the idea that users could see all the definitions for one term in one place. This could especially help policy writers be aware of all the terms they are using and even potentially help them to consolidate definitions if needed.

**Comment by cmc333333** [comment]
CM: do you think there'd be any filtering of terms based on which requirement/policy the user's currently looking at?

Jen: Um.. so yes I _think_. That’s an interesting question actually. Making sure I understand — say I’m reading the open source policy. If I click the glossary feature, are you thinking the definitions would be already filtered down to the ones defined in that document?

CM: yeah, or the relevant ones are highlighted or something

Jen: So from a “i’m clicking a term inside the open source policy” I would want to see that term’s definition as defined in that policy first, but then maybe collapsed under it, see any other definitions that term is defined as in other docs. Does that make sense?

CM: I don't know how bad the definition-overlap problem will be. it wouldn't be feasible to have a usable glossary of CFR definitions, for example

Jen: right. I don’t really expect the browsing feature to work. It’d be more search and show me what terms match my search probs

**Comment by jehlers** [comment]
Here's a sketch of what I'm thinking for viewing multiple definitions:

![image_uploaded_from_ios_1024](https://cloud.githubusercontent.com/assets/4267825/23563837/70d02e14-0016-11e7-8a8c-4865c04f2c1b.jpg)

I really like the expandable idea (as seen in the FEC glossary). Where each term could have a few expandable definitions. If you click on the term inside a specific policy document, the definition that applies most closely to that policy should be expanded. But the others are there for reference. 

Then if you start by just searching the glossary, you see the term with all its possible definitions available for you to expand and read (and go through to the document it was defined in if need be).

**Comment by donjo** [comment]
![artboard copy](https://cloud.githubusercontent.com/assets/776987/23567786/9e5fd79c-001d-11e7-816d-23c63e31cc3e.png)
![artboard](https://cloud.githubusercontent.com/assets/776987/23567785/9e5c2d68-001d-11e7-844e-3158d1576875.png)

some additional sketched up versions showing defined terms with alternate definitions
