### ISSUE TITLE
Only allow one footnote to be opened at a time (depends on #620)

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#621]

**Comment by cmc333333** [comment]
Three implementation options come to mind (there are no doubt more):

1. Redux. This is the standard for global state management, which gives it lots of points. It is, however, heavy in terms of cognitive overhead. Next.js has an [example](https://github.com/zeit/next.js/tree/canary/examples/with-redux) that uses the `next-redux-wrapper` glue. That lib ensures the state is serialized from the server. If we went down this road, I'd want us to consider throwing the URL into the store, too, so we only had one place for component state.
2. Flux-style (redux or otherwise) store which is only used by the `FootnoteCitation` component. Using multiple stores has fallen out of favor, but this has the benefit of compartmentalization. It's still quite a bit of (new) cognitive overhead.
3. Adding a static variable to the `FootnoteCitation` component. This is a simplified version of 2. Easier to understand, but also feels pretty hacky and seems likely to bite us at some point.
