### ISSUE TITLE
Ensure pop-up footnotes are accessible (depends on #620)

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#633]
Ensure that the footnote interaction is accessible, particularly to a screen reader. One potential solution is described in [this comment](https://github.com/18F/omb-eregs/issues/566#issuecomment-338236395), but that doesn't account for the popup footnotes.

**Comment by carodew** [comment]
I think it can work for pop up footnotes if you think about it in terms of moving focus?

**Comment by toolness** [comment]
oh i can do this one!

**Comment by toolness** [comment]
oh i can do this one!

**Comment by toolness** [comment]
oh i can do this one!

**Comment by toolness** [comment]
I'm logging all the bugs I'm finding related to footnote accessibility here (we can move them out into their own issues as needed):

1. Expanded footnotes don't appear to have any kind of focus style--the normal outline doesn't show, so when they have keyboard focus, it's impossible to tell.

2. When pressing the "close" button, input focus isn't explicitly set, which makes different browsers do different things.  Both Firefox and Chrome show no indication of where the focus is, and Chrome behaves especially oddly. This can be fixed by having the focus go to the related footnote link once the close button is pressed.

3. Expanding a footnote doesn't cause the NVDA screenreader to start reading the actual content of the footnote. We can probably trigger this by setting [`tabindex="-1"`](https://developer.paciellogroup.com/blog/2014/08/using-the-tabindex-attribute/) on the footnote content, and focusing it when the footnote is expanded.

4. We _might_ want to add screenreader-only text to the close button so that the screenreader label is "close footnote", to prevent any confusion about what's actually going to be closed if the user presses the button, but I'm not sure.
