### ISSUE TITLE
DATA: get as many of the IT (OFCIO) policy docs as possible 

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#779]
- [ ] Get it from other libraries
- [ ] Import into machine script to convert to HTML
- [ ] Wipe hands on pants

**Comment by cmc333333** [comment]
Starting with our test pdfs:
* [ ] M-11-29
* M-15-17 - this isn't part of the prod data
* [x] M-16-19
* [ ] M-17-02
* [ ] M-17-11
* [ ] M-17-13
* [ ] M-17-15

**Comment by cmc333333** [comment]
M-Memos which are part of the production data set, and whether or not they can be imported from pdf:

* [ ] M-96-20
* [ ] M-97-02
* [ ] M-97-07
* [ ] M-97-09
* [ ] M-97-10
* [ ] M-99-05
* [ ] M-99-18
* [ ] M-00-07
* [ ] M-00-10
* [ ] M-00-15
* [ ] M-01-05
* [ ] M-01-17
* [ ] M-02-01
* [ ] M-03-18
* [ ] M-03-22
* [ ] M-04-04
* [ ] M-04-08
* [ ] M-04-15
* [ ] M-04-16
* [ ] M-04-19
* [ ] M-04-26
* [ ] M-05-04
* [ ] M-05-08
* [ ] M-05-09
* [ ] M-05-13
* [ ] M-05-22
* [ ] M-05-23
* [ ] M-05-24
* [ ] M-05-25
* [ ] M-06-02
* [ ] M-06-15
* [ ] M-06-18
* [ ] M-06-19
* [ ] M-06-22
* [ ] M-07-18
* [ ] M-07-20
* [ ] M-08-05
* [ ] M-08-16
* [ ] M-08-22
* [ ] M-08-23
* [ ] M-08-27
* [ ] M-09-06
* [ ] M-09-12
* [ ] M-09-25
* [ ] M-09-32
* [ ] M-10-06
* [ ] M-10-11
* [ ] M-10-22
* [ ] M-10-23
* [ ] M-10-26
* [ ] M-10-24
* [ ] M-10-28
* [ ] M-11-02
* [ ] M-11-04
* [ ] M-11-06
* [ ] M-11-11
* [ ] M-11-13
* [ ] M-11-15
* [ ] M-11-24
* [ ] M-11-26
* [ ] M-11-33
* [ ] M-12-06
* [ ] M-12-09
* [ ] M-12-10
* [ ] M-12-12
* [ ] M-12-13
* [ ] M-12-14
* [ ] M-12-18
* [ ] M-12-20
* [ ] M-13-02
* [ ] M-13-08
* [ ] M-13-09
* [ ] M-13-13
* [ ] M-13-14
* [ ] M-13-17
* [ ] M-14-01
* [ ] M-14-02
* [ ] M-14-03
* [ ] M-14-06
* [ ] M-14-07
* [ ] M-14-08
* [ ] M-14-11
* [ ] M-14-12
* [ ] M-14-16
* [ ] M-15-03
* [ ] M-15-04
* [ ] M-15-05
* [ ] M-15-11
* [ ] M-15-12
* [ ] M-15-13
* [ ] M-15-14
* [ ] M-15-15
* [ ] M-15-16
* [ ] M-15-19
* [ ] M-16-02
* [ ] M-16-04
* [ ] M-16-05
* [ ] M-16-10
* [ ] M-16-11
* [ ] M-16-12
* [ ] M-16-13
* [ ] M-16-14
* [ ] M-16-15
* [ ] M-16-16
* [ ] M-16-17
* [ ] M-16-19
* [ ] M-16-20
* [ ] M-16-21
* [ ] M-16-24
* [ ] M-17-04
* [ ] M-17-06
* [ ] M-17-12
* [ ] M-17-25
* [ ] M-17-26
* [ ] M-18-02

**Comment by cmc333333** [comment]
Major findings:
* pdfminer is sometimes returning lines out of order (e.g. M-07-18). This may be particularly problematic as it's easy to miss.
* a handful of the documents contain tables, but it's not the majority
* side-by-side comparison will likely be helpful, if only due to the number of formatting errors
* we will likely need a method of emphasizing text, such as "this does *not* include ..."
* it may make sense to allow the editor to configure the pdf importer. For example, in some cases, the import is so inaccurate that it'd be more helpful to have imported everything as paragraphs
* occasionally, external links pop up in the policies. We can probably import those from the PDF. Maybe we run a link checker, too?
* often, there's a misparse where paragraph text is included in the heading prior. This may mean we'll need a relatively easy way to "split" headings
* phrases are sometimes repeated in the underlying text (it's part of the pdf data). I'm not sure how/if we should account for it (e.g. M-07-18)
* "attachments" (a separately formatted document) are common. Does it make to restart the parser for each subdocument? AKN has a relatively complex approach to attached documents which we might consider if we want to display these differently.
* at least one document (M-06-22) contained many internal (to the document) citations. I don't think it makes sense to parse these automatically, but it may be a nice annotation for editors.
* I've not seen a *need* for images, though M-06-22 ends with an "illustrative example" table, which might be better as an image.

**Comment by cmc333333** [comment]
Quick stats from the initial data set.
* 180 policies have a short name (e.g. M-01-01); 72 don't
* 161 policies' with short names begin with "M-"; 19 don't

Of the policies which have no short name:
```sql
postgres=# select count(*), policy_type from reqs_policy where omb_policy_id = '' group by policy_type;
 count |   policy_type
-------+-----------------
    13 | guidance
    19 | memorandum
     3 | plan
    11 | executive
     1 | national_action
     1 | review
    10 | law
     4 |
     9 | strategy
     1 | circular
```

**Comment by cmc333333** [comment]
Of the ~30 that I inspected, the following had significant errors:
* M-00-07 - Missing a lot of data
* M-03-18 - Table of contents clearly very off
* M-04-04 - On the border
* M-04-08 - Missing a lot of data
* M-04-15 - Table of contents clearly very off
* M-05-22 - Missing a lot of data
* M-06-18 - Missing a lot of data
