### ISSUE TITLE
Status flagging system 

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#819]
Set up status flagging system and filtering for “Imported” “Editing” “Ready for review” "Published"

**Comment by tadhg-ohiggins** [comment]
My thinking is that there are two potential workflows we need to cover:

## Import Workflow

0.  Policy exists in DB, but no document is associated with it. (blank)
1.  Text has been imported, but not checked/cleaned up. ('Cleanup')
2.  Text has been checked/cleaned up and is ready for review. ('Review')
3.  Text has been published. ('Published')

## Edit Workflow

0.  Policy exists in DB, but no document is associated with it. (blank)
1.  Text is being created/edited in the tool, but is not yet ready for
    review. ('Edit')
2.  Text is ready for review. ('Review')
3.  Text has been published. ('Published')

This gives us four potential workflow phases that a policy could be in:
(blank)
`Cleanup`
`Edit`
`Published`
`Review`

**Comment by toolness** [comment]
This looks good to me, I like it!  Maybe we should go over it w/ @austinhernandez at our MVP features list later today?

**Comment by toolness** [comment]
@tadhg-ohiggins one thing I just realized, which might have to do with this and/or #830, is the ability for us to be able to detect whether a  document has been edited at all since being bulk-imported. If it hasn't been, and if we improve our PDF importing logic in the interim, we'll likely want to re-import all the untouched documents, so that once someone _does_ get around to editing them, they'll be using the best-possible import.

**Comment by tadhg-ohiggins** [comment]
@toolness I just saw this comment; I'm not sure it makes sense for `workflow_phase` to track this (although it might), but in any case it won't fit in the current set of phases. Do you want to create a new issue for it?

**Comment by yowill** [comment]
Demoed and closed!
