### ISSUE TITLE
Use CircleCI's workflows to parallelize tests

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#859]
CircleCI allows steps to be performed in parallel via [workflows](https://circleci.com/docs/2.0/workflows). This would speed up our CI and give us more feedback (as multiple steps could fail).

**Comment by toolness** [comment]
Ooo this would be super awesome!  The tests currently take long enough to run that I grumble when I need to make a minor edit to a PR before merging, hehe.

**Comment by toolness** [comment]
Are we currently using CircleCI's [dependency caching](https://circleci.com/docs/2.0/caching/) in any way?  If not, it seems like this would be a useful first step, both because it'd speed up our current builds as-is, and then it'd be useful for test parallelization because we could use [workspaces](https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs) to store the cached dependencies, allowing them to be shared amongst different jobs... I think...

**Comment by cmc333333** [comment]
Good point about dependency caching; we aren't using it at all.
